name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: windows-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"

      - name: Build EXE
        run: make

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: sing-box-service.exe
          token: ${{ secrets.GITHUB_TOKEN }}
